In [6]:
import numpy as np ### importing numpy with alias np 

### Generating numpy array from List and Tuple

In [8]:
List = [1,2,3,4,5]

np_list = np.array(List) ### using list as input

print("Numpy array:",np_list)
print("Data type:",np_list.dtype)

Numpy array: [1 2 3 4 5]
Numpy array: int32


In [10]:
Tuple = (1,2,3,4,5)

np_tuple = np.array(Tuple)

print("Numpy array from tuple:",np_tuple)
print("Data type:",np_tuple.dtype)

Numpy array from tuple: [1 2 3 4 5]
Data type: int32


#### Generating numpy array with predefined values

In [28]:
rows = 4
cols = 4

### generating a numpy array with all 1's with given rows and cols
all_ones = np.ones((rows,cols))
print(all_ones)
print("Rows:",all_ones.size // all_ones[0].size)
print("Columns:",all_ones[0].size)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Rows: 4
Columns: 4


In [32]:
### generating a numpy array with all 0's with given rows and cols
all_zeros = np.zeros((rows,cols))
print(all_zeros)
print("Rows:",all_zeros.size // all_zeros[0].size)
print("Columns:",all_zeros[0].size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Rows: 4
Columns: 4


In [40]:
predefinedValue = 3
all_with_val = np.full((rows,cols),predefinedValue)

print(all_with_val)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [48]:
### Generating the indentity matrix using np.eye()
indentity_matrix = np.eye(3,3)
print(indentity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
### Generating array in a given range with specific quantity 
in_range_array = np.linspace(1,10,num = 5)
print(in_range_array)

[ 1.    3.25  5.5   7.75 10.  ]


In [58]:
### Generating array in a given range with specific gaps 
arange_array = np.arange(1,10,3)
print(arange_array)

[1 4 7]


### Random Number Generation

In [61]:
### generating matrix with all random numbers with uniform distribution
random_number_matrix = np.random.rand(3,3)
print(random_number_matrix)

[[0.951907   0.12389071 0.28106607]
 [0.70322112 0.5237464  0.17991817]
 [0.34198332 0.17423341 0.52709101]]


In [63]:
### generating matrix with all random numbers but with normal distribution 
normal_random_matrix = np.random.randn(3,3)
print(normal_random_matrix)

[[-0.92424481  0.84311361 -0.00415809]
 [-1.312599    1.69855672  0.06107301]
 [ 0.41131722  0.95401803  0.86242262]]


In [69]:
### generating matrix with random number within a given range 
random_in_range = np.random.randint(10,50,(3,3))
print(random_in_range)

[[29 18 15]
 [38 13 10]
 [30 27 20]]


In [71]:
### choosing random numbers from a list 
random_choice = np.random.choice([10,2,3,5],size = 4)
print(random_choice)

[ 2  3 10  3]


### Array manipulation

In [95]:
### manipulating the array 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [86]:
### reshaping the array
reshaped_array = arr.reshape(3,4)
print(reshaped_array)
print("Rows:",reshaped_array.size // reshaped_array[0].size)
print("Cols:",reshaped_array[0].size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rows: 3
Cols: 4


In [105]:
### transpose function 
transposed_array = reshaped_array.transpose()
print(transposed_array)
print("Rows:",reshaped_array.size // reshaped_array[0].size)
print("Cols:",reshaped_array[0].size)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Rows: 3
Cols: 4


In [121]:
### concatenating two numpy arrays 
arr1 = np.array([3,4,5,6])
arr2 = np.array([10,11,12])

concatenated_array = np.concatenate([arr1,arr2])
### co
print(concatenated_array)

[ 3  4  5  6 10 11 12]


### Mathematic functions using numpy array

In [126]:
sample_array = np.random.randint(0,100,12)

[91 59 85 20 70  8 68 21 23 79 24 18]


In [128]:
### mean of all arrays 
print(np.mean(sample_array))

47.166666666666664


In [130]:
### median of all arrays 
print(np.median(sample_array))

41.5


In [136]:
### standard deviation of elements in given array arrays 
print(np.std(sample_array))

29.424574008055846


In [138]:
### min and max of elements 
print("Minimum elements:",np.min(sample_array))
print("Maximum elements:",np.max(sample_array))

Minimum elements: 8
Maximum elements: 91


In [140]:
### Find the sum of all elements 
print("Sum of all elements:",np.sum(sample_array))

Sum of all elements: 566


In [142]:
### Find the product of all elements 
print("Sum of all elements:",np.prod(sample_array))

Sum of all elements: 183160832


In [146]:
### finding cumulative sum and product of all elements 
print("Cumulatative sum of all elements",np.cumsum(sample_array))
print("Cumulative product of all elements:",np.cumprod(sample_array))

Cumulatative sum of all elements [ 91 150 235 255 325 333 401 422 445 524 548 566]
Cumulative product of all elements: [         91        5369      456365     9127300   638911000   816320704
  -324766976  1769828096  2051340544 -1152854272 -1898698752   183160832]


### Linear Alzebra using Numpy

In [159]:
matrix1 = np.array([[1,2,3],[4,3,5],[29,13,49]])
matrix2 = np.array([[32,322,3],[32,13,13],[443,433,22]])

print("Matrix 1:")
print(matrix1,end = '\n\n')

print("Matrix 2:")
print(matrix2)

Matrix 1:
[[ 1  2  3]
 [ 4  3  5]
 [29 13 49]]

Matrix 2:
[[ 32 322   3]
 [ 32  13  13]
 [443 433  22]]


In [165]:
### dot product
dot_product = np.dot(matrix1,matrix2)
print(dot_product)

[[ 1425  1647    95]
 [ 2439  3492   161]
 [23051 30724  1334]]


In [169]:
### matrix multiplication 
matrix_mul = np.matmul(matrix1,matrix2)
print(matrix_mul)

[[ 1425  1647    95]
 [ 2439  3492   161]
 [23051 30724  1334]]


In [187]:
### inversion of given matrix 
inverse_mat = np.linalg.inv(matrix_mul)
print("Inverse of matrix:")
print(inverse_mat,end = '\n\n')

###  verfiying the inversion of matrix
print("Identity matrix:")
print(matrix_mul @ inverse_mat)

Inverse of matrix:
[[ 1.55695414e-03 -3.89828396e-03  3.59605003e-04]
 [-2.47172060e-03  1.56051383e-03 -1.23157948e-05]
 [ 3.00238335e-02  3.14198774e-02 -5.18055806e-03]]

Identity matrix:
[[ 1.00000000e+00  2.42861287e-16  6.41847686e-17]
 [-1.56125113e-16  1.00000000e+00  1.57859836e-16]
 [ 2.28983499e-16  6.52256027e-16  1.00000000e+00]]


In [189]:
### Determinant of a matrix 
print(np.linalg.det(matrix_mul))

-185128125.0


In [203]:
### Solving set of linear equation using numpy 

# Linear equation:
   # 2 * x + 3 * y + 3 * z = 18
   #     x +     y +     z = 7
   # 2 * x + 4 * y +     z = 19
### expected solution : x = 3,y = 3,z = 1

coef = np.array([[2,3,3],[1,1,1],[2,4,1]])
sol  = np.array([18,7,19])

### result 
print(np.linalg.solve(coef,sol))

[3. 3. 1.]
